# Copyright 2025 CIQ, Inc. All rights reserved.
version: v1
jobs:
  xfce4-desktop:
    env:
      - HOME=/tmp/home
      - ANSYSLMD_LICENSE_FILE={{.AnsyslmdLicenseFile}}
    image:
      uri: { { .AnsysFluentDesktopContainerURI: "" }: "" }
      secret: { { .AnsysFluentDesktopContainerOciSecret: "" }: "" }
    mounts:
      data:
        location: /data
    policy:
      timeout:
        execute: { { .Timeout: "" }: "" }
    command:
      - /bin/sh
      - "-c"
      - /usr/local/bin/start-vncserver.sh
    resource:
      cpu:
        cores: { { .FluentDesktopCores: "" }: "" }
        affinity: NUMA
      memory:
        size: { { .FluentDesktopMemory: "" }: "" }
volumes:
  data:
    reference: { { .Volume: "" }: "" }
