# Copyright 2025 CIQ, Inc. All rights reserved.
{{- $ver := .AnsysVersion }}
{{- $ansys_version_number := printf "v%s%s" (substr 2 4 $ver) (substr 5 6 $ver) }}
version: v1
jobs:
  xfce4-desktop:
    env:
      - HOME=/tmp/home
      - ANSYSLMD_LICENSE_FILE={{.AnsyslmdLicenseFile}}
    image:
      uri: {{.AnsysFluentDesktopContainerURI}}
      secret: {{.AnsysFluentDesktopContainerOciSecret}}
    mounts:
      data:
        location: /data
    policy:
      timeout:
        execute: {{.Timeout}}
    command:
      - /bin/sh
      - '-c'
      - |
        export PATH={{.AnsysInstallDir}}/{{$ansys_version_number}}/fluent/bin:$PATH
        /usr/local/bin/start-vncserver.sh
    resource:
      cpu:
        cores: {{.FluentDesktopCores}}
        affinity: NUMA
      memory:
        size: {{.FluentDesktopMemory}}
volumes:
  data:
    reference: {{.Volume}}
