# Copyright 2025 CIQ, Inc. All rights reserved.
version: v1
jobs:
  printer:
    image:
      uri: { { .Container: "" }: "" }
    policy:
      timeout:
        execute: 1m{{.Seconds}}s
    command:
      - /bin/sh
      - "-c"
      - for i in $(seq 1 {{.Seconds}}); do echo $i; sleep 1; done
    resource:
      cpu:
        cores: 1
      memory:
        size: 1GB
