# Copyright 2025 CIQ, Inc. All rights reserved.

{{- $buildNumber := .StarccmBuildNumber }}
{{- if eq .StarccmPrecision "double" }}
  {{- $buildNumber = printf "%s-R8" .StarccmBuildNumber }}
{{- end }}
{{- $datamount := "/data" }}

version: v4

volumes:
  data:
    reference: {{.Volume}}

defaults:
  job:
    mounts:
      {{ $datamount }}: data

jobs:
  starccm-acoustic-wave-simulation:
    image:
      uri: >-
        {{.StarccmContainerURI}}:{{.StarccmVersion}}-{{.StarccmPrecision}}
      secret: {{.StarccmContainerOciSecret}}
    env:
      - CDLMD_LICENSE_FILE={{.CdlmdLicenseFile}}
      - STARCCM_POD_KEY={{.StarccmPodKey}}
    cwd: {{ $datamount }}
    script: |
      #!/bin/sh
      set -e

      WORKDIR="{{ $datamount }}/simcenter-starccm-acoustic-wave-$FB_WORKFLOW_ID"
      mkdir -p "$WORKDIR"
      cd "$WORKDIR"

      cp /StarCCM+VerificationSuite/VerificationData/acousticWave/acousticWave_PlanarWave_final.sim .

      export PATH=/opt/Siemens/{{ $buildNumber }}/STAR-CCM+{{ $buildNumber }}/star/bin:$PATH

      starccm+ -podkey $STARCCM_POD_KEY -rsh ssh -power -batch -np {{.StarccmCores}} -load acousticWave_PlanarWave_final.sim
    resource:
      cpu:
        cores: {{.StarccmCores}}
        affinity: NUMA
      memory:
        size: {{.StarccmMemory}}
    policy:
      timeout:
        execute: 30m
