values:
  - name: "CdlmdLicenseFile"
    display_name: "Simcenter STAR-CCM+ network license server (CDLMD_LICENSE_FILE)"
    string_value: "1999@flex.cd-adapco.com"
    display_category: "Licensing"
  - name: "StarccmPodKey"
    display_name: "Fuzzball environment variable secret containing Simcenter STAR-CCM+ Power on Demand license key."
    string_value: "secret://user/STARCCM_POD_KEY"
    display_category: "Licensing"
  - name: "StarccmVersion"
    display_name: "Version of Simcenter STAR-CCM+."
    string_value: "2506"
    display_category: "Installation"
  - name: "StarccmPrecision"
    display_name: "Precision of Simcenter STAR-CCM+ installation (double or mixed)"
    string_value: "double"
    display_category: "Installation"
  - name: "StarccmBuildNumber"
    display_name: "Build number of Simcenter STAR-CCM+ installation"
    string_value: "20.04.007"
    display_category: "Installation"
  - name: "StarccmContainerURI"
    display_name: "URI of Simcenter STAR-CCM+ container that will be used."
    string_value: "oras://depot.ciq.com/simcenter/simcenter-application-images/simcenter_starccm.sif"
    display_category: "Container"
  - name: "StarccmContainerOciSecret"
    display_name: "Fuzzball secret to access Simcenter STAR-CCM+ container"
    string_value: "secret://user/DEPOT_TOKEN"
    display_category: "Container"
  - name: "Volume"
    display_name: "Volume to store Simcenter STAR-CCM+ input and results"
    string_value: "volume://user/persistent/data"
    display_category: "Storage"
  - name: "StarccmCores"
    display_name: "How many CPU cores to allocate to run Simcenter STAR-CCM+"
    uint_value: 4
    display_category: "Resources"
  - name: "StarccmMemory"
    display_name: "How much memory to allocate to run Simcenter STAR-CCM+."
    string_value: "8GiB"
    display_category: "Resources"
