# Copyright 2025 CIQ, Inc. All rights reserved.
version: v1
jobs:
  cfx-static-mixer:
    env:
      - ANSYSLMD_LICENSE_FILE={{.AnsyslmdLicenseFile}}
    image:
      uri: {{.AnsysCfxContainerURI}}
      secret: {{.AnsysCfxContainerOciSecret}}
    mounts:
      data:
        location: /data
    policy:
      timeout:
        execute: 30m0s
    cwd: /data
    command:
      - /bin/sh
      - '-c'
      - >-
        ANSYS_VERSION={{.AnsysVersion}}
        ANSYS_VERSION_NUMBER=$(echo ${ANSYS_VERSION/R/} | cut -c 3-)

        mkdir ansys-cfx-static-mixer-example-$FB_WORKFLOW_ID;
        cd ansys-cfx-static-mixer-example-$FB_WORKFLOW_ID;
        cp {{.AnsysInstallDir}}/v${ANSYS_VERSION_NUMBER}/CFX/examples/StaticMixer.def .

        {{.AnsysInstallDir}}/v${ANSYS_VERSION_NUMBER}/CFX/bin/cfx5solve -def StaticMixer.def -par-dist "$(hostname)*{{.CfxCores}}";
    resource:
      cpu:
        cores: {{.CfxCores}}
        affinity: NUMA
      memory:
        size: {{.CfxMemory}}
volumes:
  data:
    reference: {{.Volume}}
