# Copyright 2025 CIQ, Inc. All rights reserved.
{{- $ver := .AnsysVersion }}
{{- $ansys_version_number := printf "v%s%s" (substr 2 4 $ver) (substr 5 6 $ver) }}
version: v1
jobs:
  cfx-static-mixer:
    env:
      - ANSYSLMD_LICENSE_FILE={{.AnsyslmdLicenseFile}}
    image:
      uri: {{.AnsysCfxContainerURI}}
      secret: {{.AnsysCfxContainerOciSecret}}
    mounts:
      data:
        location: /data
    policy:
      timeout:
        execute: 30m0s
    cwd: /data
    command:
      - /bin/sh
      - '-c'
      - >-
        export PATH={{.AnsysInstallDir}}/{{$ansys_version_number}}/CFX/bin:$PATH;

        mkdir ansys-cfx-static-mixer-example-$FB_WORKFLOW_ID;
        cd ansys-cfx-static-mixer-example-$FB_WORKFLOW_ID;

        cfx5solve -eg StaticMixer -par-dist "$(hostname)*{{.CfxCores}}";

        LATEST_CFX_LOG_FILE=$(ls -1t StaticMixer_*.out 2>/dev/null | head -n 1)

        if [ -n "$LATEST_CFX_LOG_FILE" ]; then
          cat $LATEST_CFX_LOG_FILE;
        else
          echo "No CFX log files found.";
        fi

    resource:
      cpu:
        cores: {{.CfxCores}}
        affinity: NUMA
      memory:
        size: {{.CfxMemory}}
volumes:
  data:
    reference: {{.Volume}}
