values:
  - name: UserPassword
    display_name: User password for accessing Unsloth/Jupyter frontends.
    string_value: ""
    display_category: Configuration

  - name: ScratchVolume
    display_name: Ephemeral volume mounted at /scratch. Required.
    string_value: volume://user/ephemeral
    display_category: Storage
  - name: DataVolume
    display_name: >-
      Volume housing your Unsloth/Jupyter workspace. Mounted at /data. Use a persistent
      volume to preserve your workspace for future sessions. Defaults to an ephemeral
      volume for testing. Required.
    string_value: volume://user/ephemeral
    display_category: Storage
  - name: UnslothDirectory
    display_name: Absolute path to your unsloth data directory (workspace and jupyter notebooks). Required.
    string_value: "/data/unsloth"
    display_category: Storage
  - name: HFHomeDirectory
    display_name: >-
      Absolute path to your huggingface cache directory. Allows unsloth studio to discover cached
      models from HuggingFace.
    string_value: "/data/.cache/huggingface"
    display_category: Storage

  - name: CpuCores
    display_name: Cores to allocate for the Unsloth/Jupyter service.
    uint_value: 2
    display_category: Resources
  - name: Memory
    display_name: Amount of memory to allocate for the Unsloth/Jupyter service.
    string_value: 16GiB
    display_category: Resources
  - name: NumGPUs
    display_name: Number of GPU devices to request.
    uint_value: 1
    display_category: Resources
  - name: ModelGPU
    display_name: GPU model to request.
    string_value: NVIDIA L4
    display_category: Resources

  - name: UnslothImage
    display_name: Unsloth container image to use.
    string_value: docker://unsloth/unsloth:2026.4.6-pt2.10.0-vllm-0.16.0-cu12.8-studio-release-v0.1.36-beta-fixes
    display_category: Versions
