values:
  - name: Volumes
    display_name: |
      Comma separated list of volumes to mount. These are Fuzzball volume references
      such as `volume://group/persistent/data`. By default the example volume would be available
      as `group/persistent/data` in the file browser. If you would like to use a custom path for
      a particular volume in the file browser, you can specify it like this:
      `volume://group/persistent/data:data`. The leading slash is optional.
    string_value: "volume://user/ephemeral:data"

  - name: Container
    display_name: CloudCommander container
    string_value: "docker://coderaiser/cloudcmd:19.19.0"
    display_category: Container

  - name: "ServiceScope"
    display_name: |
      Who can access this CloudCommander instance. Defaults to 'user'.
    string_value: user
    options_input:
      options: [user, group, organization]
    display_category: "Access"
