# Copyright 2025 CIQ, Inc. All rights reserved.
{{- $port := (randInt 10000 30000) }}

version: v4

services:
 jupyter:
    image:
      uri: oras://depot.ciq.com/fuzzball/fuzzball-applications/jupyter-{{.NotebookType}}-notebook.sif
      secret: {{.DepotSecret}}
    mounts:
      /home/jovyan:
        volume: stable-diffusion-storage
    persist: true
    network:
      ports:
        - name: web
          port: {{ $port }}
          protocol: tcp
      endpoints:
        - name: jupyter
          type: path
          port-name: web
          protocol: http
          scope: user
    readiness-probe:
      exec:
        command:
          - /bin/sh
          - '-c'
          - jupyter server list &> /dev/null
      period-seconds: 5
      timeout-seconds: 5
      initial-delay-seconds: 10
    env:
      - HOME=/home/jovyan
      - NB_USER=jovyan
    script: |
      #!/bin/bash
      set -e
      mkdir -p "${HOME}/.jupyter"
      cat <<__EOF__ > "${HOME}/.jupyter/jupyter_server_config.py"
      c = get_config()
      c.ServerApp.ip = "0.0.0.0"
      c.ServerApp.port = {{ $port }}
      c.ServerApp.open_browser = False
      c.IdentityProvider.token = ""
      c.PasswordIdentityProvider.password_required = False
      c.ServerApp.root_dir = "$HOME"
      c.ServerApp.allow_credentials = False
      c.ServerApp.default_url = '/lab'
      c.ServerApp.base_url = "${FB_ENDPOINT_PATH_JUPYTER}"
      c.Application.log_level = "INFO"
      __EOF__

      /opt/conda/bin/jupyter server
    resource:
      cpu:
        cores: {{.JupyterCores}}
        affinity: NUMA
      memory:
        size: {{.JupyterMemory}}
    depends-on:
      - name: txt2img
        status: FINISHED

jobs:
  txt2img:
    cwd: /stable-diffusion
    env:
      - PYTHONUNBUFFERED=TRUE
      - >-
        TXT2IMG_PROMPT={{.StableDiffusionTxt2ImgPrompt}}
      - TORCH_HOME=/data/txt2img/.cache/torch
      - HF_HOME=/data/txt2img/.cache/huggingface
    image:
      uri: >-
        {{.StableDiffusionContainerURI}}
      secret: {{.DepotSecret}}
    mounts:
      /data:
        volume: stable-diffusion-storage
    script: |
      #!/bin/sh
      outdir=/data/txt2img/$(date +%Y-%m-%d-%H:%M:%S); mkdir -p "${outdir}"
      echo "${TXT2IMG_PROMPT}" >"${outdir}/prompt.txt"
      python3 /stable-diffusion/scripts/txt2img.py --prompt "${TXT2IMG_PROMPT}" \
          --ckpt /data/txt2img/sd-v1-4.ckpt --outdir "${outdir}" --seed $RANDOM
    depends-on:
      - name: prefetch
        status: FINISHED
    resource:
      cpu:
        cores: {{.StableDiffusionCores}}
        affinity: NUMA
      memory:
        size: {{.StableDiffusionMemory}}
      devices:
        nvidia.com/gpu: {{.StableDiffusionGPUs}}
  prefetch:
    image:
      uri: {{.CurlContainerURI}}
      secret: {{.DepotSecret}}
    mounts:
      /data:
        volume: stable-diffusion-storage
    script: |
      #!/bin/sh
      mkdir -p /data/txt2img
      cd /data/txt2img
      test -f sd-v1-4.ckpt \
      || curl -LO https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt?download=true
    resource:
      cpu:
        cores: 1
        affinity: NUMA
      memory:
        size: 1GiB
volumes:
  stable-diffusion-storage:
    reference: {{.Volume}}
