# Copyright 2025 CIQ, Inc. All rights reserved.
version: v1
jobs:
  jupyter:
    image:
      uri: oras://depot.ciq.com/fuzzball/fuzzball-applications/jupyter-{{.NotebookType}}-notebook.sif
      secret: { { .DepotSecret: "" }: "" }
    mounts:
      stable-diffusion-storage:
        location: /home/jovyan
    env:
      - HOME=/home/jovyan
    command:
      - /bin/sh
      - "-c"
      - |
        export NB_USER=$(whoami)
        test -d $HOME || mkdir $HOME
        echo
        echo "Accessing Jupyter requires port-forwarding via the CLI:"
        echo
        echo "# fuzzball workflow port-forward ${FB_WORKFLOW_ID} jupyter 8888:8888"
        echo
        echo "Then navigate to http://localhost:8888"
        echo
        /opt/conda/bin/jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token="${JUPYTER_TOKEN}" --notebook-dir="${HOME}"
    resource:
      cpu:
        cores: { { .JupyterCores: "" }: "" }
        affinity: NUMA
      memory:
        size: { { .JupyterMemory: "" }: "" }
    policy:
      timeout:
        execute: { { .JupyterTimeout: "" }: "" }
    requires:
      - txt2img
  txt2img:
    cwd: /stable-diffusion
    env:
      - PYTHONUNBUFFERED=TRUE
      - >-
        TXT2IMG_PROMPT={{.StableDiffusionTxt2ImgPrompt}}
      - TORCH_HOME=/data/txt2img/.cache/torch
      - HF_HOME=/data/txt2img/.cache/huggingface
    image:
      uri: >-
        {{.StableDiffusionContainerURI}}
      secret: { { .DepotSecret: "" }: "" }
    mounts:
      stable-diffusion-storage:
        location: /data
    command:
      - /bin/sh
      - "-c"
      - >-
        outdir=/data/txt2img/$(date +%Y-%m-%d-%H:%M:%S); mkdir -p "${outdir}"; echo "${TXT2IMG_PROMPT}" >"${outdir}/prompt.txt"; python3 /stable-diffusion/scripts/txt2img.py --prompt "${TXT2IMG_PROMPT}" --ckpt /data/txt2img/sd-v1-4.ckpt --outdir "${outdir}" --seed $RANDOM
    requires:
      - prefetch
    resource:
      cpu:
        cores: { { .StableDiffusionCores: "" }: "" }
        affinity: NUMA
      memory:
        size: { { .StableDiffusionMemory: "" }: "" }
      devices:
        nvidia.com/gpu: { { .StableDiffusionGPUs: "" }: "" }
  prefetch:
    image:
      uri: { { .CurlContainerURI: "" }: "" }
      secret: { { .DepotSecret: "" }: "" }
    mounts:
      stable-diffusion-storage:
        location: /data
    command:
      - /bin/sh
      - "-c"
      - >-
        mkdir -p /data/txt2img; cd /data/txt2img; test -f sd-v1-4.ckpt || curl -LO https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt?download=true
    resource:
      cpu:
        cores: 1
        affinity: NUMA
      memory:
        size: 1GiB
volumes:
  stable-diffusion-storage:
    reference: { { .Volume: "" }: "" }
