# Copyright 2025 CIQ, Inc. All rights reserved.

{{- $datavol := trim .DataVolume }}
{{- $scratchvol := trim .ScratchVolume }}
{{- $homevol := trim .HomeVolume }}
{{- if not $scratchvol }}
  {{- fail "ScratchVolume is required" }}
{{- end }}
{{- $datamount := "/data" }}
{{- $scratchmount := "/scratch" }}
{{- $home := "/home/user" }}
{{- if not $homevol }}
  {{ $home = $scratchmount }}
{{- end }}
{{- $port := randInt 10000 32000 }}

version: v1

volumes:
{{- if $datavol }}
  data:
    reference: {{ $datavol }}
{{- end }}
{{- if $homevol }}
  home:
    reference: {{ $homevol }}
{{- end }}
  scratch:
    reference: {{ $scratchvol }}

services:
  rstudio:
    network:
      ports:
        - name: rstudio-port
          protocol: tcp
          port: {{ $port }}
      endpoints:
        - name: rstudio
          port-name: rstudio-port
          protocol: http
          type: subdomain
          scope: {{ .ServiceScope }}
    image:
      uri: {{ .ContainerImage }}
    mounts:
{{- if $datavol }}
      data:
        location: {{ $datamount }}
{{- end }}
{{- if $homevol }}
      home:
        location: {{ $home }}
{{- end }}
      scratch:
        location: {{ $scratchmount }}
    # cwd becomes the home dir in /etc/passwd which makes RStudio Server *much* happier
    cwd: {{ $home }}
    persist: true
    script: |
        #!/bin/bash

        # tmpdir is small enough that R package installations will fail. Need scratch
        TMPDIR="{{- $scratchmount }}/tmp"
        mkdir "$TMPDIR"

        # some setup
        USER=$(id -un)
        USERNAME=$USER
        DEFAULT_USER=$USER
        HOME="{{- $home }}"
        export USER USERNAME DEFAULT_USER TMPDIR HOME

        # configuration
        rstudio_dir="$(mktemp -d /tmp/XXXXXX)"  # still want this in /tmp
        mkdir -p "${rstudio_dir}"/{config,logs,server-data,server-working-dir,db}

        # make sure the user library comes before the standard lib
        cat $R_HOME/etc/Rprofile.site > "${rstudio_dir}/config/Rprofile.site"
        cat >> "${rstudio_dir}/config/Rprofile.site" <<EOF

        .libPaths(.expand_R_libs_env_var('$HOME/R/%a/%V'))
        EOF
        export R_PROFILE="${rstudio_dir}/config/Rprofile.site"
        mkdir -p "$(R -s -e "cat(.expand_R_libs_env_var('$HOME/R/%a/%V'))")"

        # https://docs.posit.co/ide/server-pro/admin/server_management/core_administrative_tasks.html
        cat > "${rstudio_dir}/config/logging.conf" << EOF
        [*]
        log-level=debug
        logger-type=file
        log-dir=${rstudio_dir}/logs
        EOF

        cat > "${rstudio_dir}/config/database.conf" << EOF
        directory=$rstudio_dir/db
        EOF

        cat > "${rstudio_dir}/config/rsession.conf" << EOF
        session-rprofile-on-resume-default=true
        session-timeout-minutes=0
        copilot-enabled=1
        session-default-working-dir=$HOME
        session-default-new-project-dir=$HOME
        restrict-directory-view=1
        EOF

        env > "${rstudio_dir}/config/env-vars"

        cat > "${rstudio_dir}/config/rserver.conf" << EOF
        # access is controlled via service end point scope
        auth-none=1
        www-address=0.0.0.0
        www-frame-origin=same
        www-port={{- $port }}
        www-verify-user-agent=no
        server-daemonize=no
        server-data-dir=$rstudio_dir/server-data
        server-pid-file=$rstudio_dir/rstudio.pid
        server-user=$USER
        server-working-dir=$rstudio_dir/server-working-dir
        rsession-path=${rstudio_dir}/config/rsession.sh
        EOF

        cat > "${rstudio_dir}/config/rsession.sh" << EOF
        #!/bin/bash
        # re-exporting the environment
        $(env | grep -v '^_' | sed 's/^/export /')
{{- if not $homevol }}
        # copy, don't symlink if the home dir with the cache is ephemeral
        export RENV_CONFIG_CACHE_SYMLINKS=FALSE
{{- end }}
        /usr/lib/rstudio-server/bin/rsession "\$@"
        EOF
        chmod +x "${rstudio_dir}/config/rsession.sh"

        # Ensure rserver is available before attempting to start it
        if ! command -v rserver >/dev/null 2>&1; then
            echo "Error: 'rserver' binary not found in PATH. Cannot start RStudio Server." >&2
            exit 1
        fi

        RSTUDIO_DATA_HOME="$rstudio_dir/server-data" \
        RSTUDIO_CONFIG_DIR="$rstudio_dir/config" \
        rserver || {
            status=$?
            echo "Error: 'rserver' failed to start with exit code ${status}." >&2
            exit "$status"
        }
    resource:
      cpu:
        cores: {{ .Cores }}
      memory:
        size: {{ .Memory }}
