# Copyright 2025 CIQ, Inc. All rights reserved.
version: v1
volumes:
  openfoam-data-volume:
    name: openfoam-data-volume
    reference: volume://user/ephemeral

jobs:

  preprocess-model:
    image:
      uri: "{{.OpenFoamContainerUri}}"
    env:
      - WM_PROJECT_DIR={{.WmProjectDir}}
    command:
      - "/bin/bash"
      - "-c"
      - |
        cp -r $WM_PROJECT_DIR/tutorials/incompressible/simpleFoam/motorBike .;
        cp motorBike/system/decomposeParDict.6 motorBike/system/decomposeParDict;

        cd motorBike

        SUBDOMAINS=$(( {{.SimulationOrMeshJobCores}} * {{.SimulationOrMeshJobNodes}} ))
        sed -i "s/numberOfSubdomains\ 6/numberOfSubdomains\ ${SUBDOMAINS}/g" system/decomposeParDict;
        sed -i 's/\(3 2 1\)/{{.Coefficients}}/g' system/decomposeParDict;
        cat system/decomposeParDict;

        source $WM_PROJECT_DIR/etc/bashrc;
        mkdir -p constant/triSurface;
        cp -f $FOAM_TUTORIALS/resources/geometry/motorBike.obj.gz constant/triSurface/;
        surfaceFeatureExtract;
        blockMesh;
        decomposePar;
    resource:
      cpu:
        cores: {{.UtilityJobCores}}
        affinity: NUMA
      memory:
        size: {{.UtilityJobMemory}}
    cwd: /data
    mounts:
      openfoam-data-volume:
        location: /data

  snappy-hex-mesh:
    image:
      uri: "{{.OpenFoamContainerUri}}"
    env:
      - WM_PROJECT_DIR={{.WmProjectDir}}
    command: ["/bin/bash", "-c", "source $WM_PROJECT_DIR/etc/bashrc; snappyHexMesh -overwrite -parallel;"]
    multinode:
      nodes: {{.SimulationOrMeshJobNodes}}
      implementation: openmpi
    resource:
      cpu:
        cores: {{.SimulationOrMeshJobCores}}
        affinity: NUMA
      memory:
        size: {{.SimulationOrMeshJobMemory}}
    cwd: /data/motorBike
    mounts:
      openfoam-data-volume:
        location: /data
    requires: ["preprocess-model"]

  toposet:
    image:
      uri: "{{.OpenFoamContainerUri}}"
    env:
      - WM_PROJECT_DIR={{.WmProjectDir}}
    command: ["/bin/bash", "-c", "source $WM_PROJECT_DIR/etc/bashrc; topoSet -parallel;"]
    multinode:
      nodes: {{.SimulationOrMeshJobNodes}}
      implementation: openmpi
    resource:
      cpu:
        cores: {{.SimulationOrMeshJobCores}}
        affinity: NUMA
      memory:
        size: {{.SimulationOrMeshJobMemory}}
    cwd: /data/motorBike
    mounts:
      openfoam-data-volume:
        location: /data
    requires: ["snappy-hex-mesh"]

  set-initial-conditions:
    image:
      uri: "{{.OpenFoamContainerUri}}"
    env:
      - WM_PROJECT_DIR={{.WmProjectDir}}
    command:
      - "/bin/bash"
      - "-c"
      - |
        source $WM_PROJECT_DIR/etc/bashrc;
        source /usr/lib/openfoam/openfoam2212/bin/tools/RunFunctions;
        restore0Dir -processor;
    resource:
      cpu:
        cores: {{.UtilityJobCores}}
        affinity: NUMA
      memory:
        size: {{.UtilityJobMemory}}
    cwd: /data/motorBike
    mounts:
      openfoam-data-volume:
        location: /data
    requires: ["toposet"]

  patch-summary:
    image:
      uri: "{{.OpenFoamContainerUri}}"
    env:
      - WM_PROJECT_DIR={{.WmProjectDir}}
    command: ["/bin/bash", "-c", "source $WM_PROJECT_DIR/etc/bashrc; patchSummary -parallel;"]
    multinode:
      nodes: {{.SimulationOrMeshJobNodes}}
      implementation: openmpi
    resource:
      cpu:
        cores: {{.SimulationOrMeshJobCores}}
        affinity: NUMA
      memory:
        size: {{.SimulationOrMeshJobMemory}}
    cwd: /data/motorBike
    mounts:
      openfoam-data-volume:
        location: /data
    requires: ["set-initial-conditions"]

  potential-foam:
    image:
      uri: "{{.OpenFoamContainerUri}}"
    env:
      - WM_PROJECT_DIR={{.WmProjectDir}}
    command: ["/bin/bash", "-c", "source $WM_PROJECT_DIR/etc/bashrc; potentialFoam -writephi -parallel"]
    multinode:
      nodes: {{.SimulationOrMeshJobNodes}}
      implementation: openmpi
    resource:
      cpu:
        cores: {{.SimulationOrMeshJobCores}}
        affinity: NUMA
      memory:
        size: {{.SimulationOrMeshJobMemory}}
    cwd: /data/motorBike
    mounts:
      openfoam-data-volume:
        location: /data
    requires: ["patch-summary"]

  check-mesh:
    image:
      uri: "{{.OpenFoamContainerUri}}"
    env:
      - WM_PROJECT_DIR={{.WmProjectDir}}
    command: ["/bin/bash", "-c", "source $WM_PROJECT_DIR/etc/bashrc; checkMesh -parallel -writeFields '(nonOrthoAngle)' -constant"]
    multinode:
      nodes: {{.SimulationOrMeshJobNodes}}
      implementation: openmpi
    resource:
      cpu:
        cores: {{.SimulationOrMeshJobCores}}
        affinity: NUMA
      memory:
        size: {{.SimulationOrMeshJobMemory}}
    cwd: /data/motorBike
    mounts:
      openfoam-data-volume:
        location: /data
    requires: ["potential-foam"]

  simple-foam:
    image:
      uri: "{{.OpenFoamContainerUri}}"
    env:
      - WM_PROJECT_DIR={{.WmProjectDir}}
    command: ["/bin/bash", "-c", "source $WM_PROJECT_DIR/etc/bashrc; simpleFoam -parallel"]
    multinode:
      nodes: {{.SimulationOrMeshJobNodes}}
      implementation: openmpi
    resource:
      cpu:
        cores: {{.SimulationOrMeshJobCores}}
        affinity: NUMA
      memory:
        size: {{.SimulationOrMeshJobMemory}}
    cwd: /data/motorBike
    mounts:
      openfoam-data-volume:
        location: /data
    requires: ["check-mesh"]

  reconstruct-mesh:
    image:
      uri: "{{.OpenFoamContainerUri}}"
    env:
      - WM_PROJECT_DIR={{.WmProjectDir}}
    command:
      - "/bin/bash"
      - "-c"
      - |
        source $WM_PROJECT_DIR/etc/bashrc;
        reconstructParMesh -constant;
        reconstructPar -latestTime;
    resource:
      cpu:
        cores: {{.UtilityJobCores}}
        affinity: NUMA
      memory:
        size: {{.UtilityJobMemory}}
    cwd: /data/motorBike
    mounts:
      openfoam-data-volume:
        location: /data
    requires: ["simple-foam"]

  tar-results:
    image:
      uri: "{{.OpenFoamContainerUri}}"
    env:
      - WM_PROJECT_DIR={{.WmProjectDir}}
    command: ["/bin/bash", "-c", "tar -zcvf openfoam-results.tar.gz motorBike"]
    resource:
      cpu:
        cores: {{.UtilityJobCores}}
        affinity: NUMA
      memory:
        size: {{.UtilityJobMemory}}
    cwd: /data
    mounts:
      openfoam-data-volume:
        location: /data
    requires: ["reconstruct-mesh"]
