values:
  - name: OpenFoamVersion
    display_name: Version of OpeanFoam to use. Will be used as the tag for the docker container.
    string_value: "2412"
    display_category: OpenFOAM Settings
  - name: WmProjectDir
    display_name: Root path of the openfoam lib directory. Do not include version - OpenFoamVersion will be used.
    string_value: /usr/lib/openfoam/openfoam
    display_category: OpenFOAM Settings

  - name: OpenFoamContainerUri
    display_name: URI for the OpenFOAM docker image to use for this workflow. Do not include a tag - OpenFoamVersion will be used.
    string_value: docker://opencfd/openfoam-default
    display_category: Container

  - name: ScratchVolume
    display_name: Scratch volume for temporary storage. Required.
    string_value: volume://user/ephemeral
    display_category: Storage
  - name: DataVolume
    display_name: Data volume for saving results directory should be saved to. Leave empty to skip.
    string_value: ""
    display_category: Storage
  - name: ResultPath
    display_name: Directory to save results to. Can be an absolute path to a local directory on your DataVolume or an s3 path.
    string_value: ""
    display_category: I/O
  - name: ResultName
    display_name: Basename of result tar archive (S3) or directory (DataVolume). A timestamp will be appended to create unique file names.
    string_value: openfoam-motorbike
    display_category: I/O
  - name: S3Secret
    display_name: Secret URI for access to the S3Bucket (if using AWS S3).
    string_value: ""
    display_category: Storage

  - name: UtilityJobCores
    display_name: CPU cores to allocate for the utility jobs.
    uint_value: 1
    display_category: Resources
  - name: UtilityJobMemory
    display_name: Memory to allocate for the utility jobs.
    string_value: 1GiB
    display_category: Resources
  - name: SimulationOrMeshJobCores
    display_name: CPU cores to allocate for the OpenFOAM processing jobs.
    uint_value: 6
    display_category: Resources
  - name: SimulationOrMeshJobNodes
    display_name: Number of nodes to allocate for the OpenFOAM processing jobs.
    uint_value: 1
    display_category: Simulation Settings
  - name: SimulationOrMeshJobMemory
    display_name: Memory to allocate for the OpenFOAM processing jobs.
    string_value: 4GiB
    display_category: Resources
  - name: Coefficients
    display_name: Coefficients to be used in DecomposeParDict. Must be factors of numberOfSubdomains (SimulationOrMeshJobCores * SimulationOrMeshJobNodes).
    string_value: 3 2 1
    display_category: Simulation Settings
