values:
  - name: OpenFoamContainerUri
    display_name: URI for the OpenFOAM docker image to use for this workflow
    string_value: docker://opencfd/openfoam-default:2212
  - name: WmProjectDir
    display_name: Environmental variable for the OpenFOAM project directory
    string_value: /usr/lib/openfoam/openfoam2212
  - name: UtilityJobCores
    display_name: CPU cores to allocate for the utility jobs
    uint_value: 1
  - name: UtilityJobMemory
    display_name: Memory to allocate for the utility jobs
    string_value: 1GiB
  - name: SimulationOrMeshJobCores
    display_name: CPU cores to allocate for the OpenFOAM processing jobs
    uint_value: 6
  - name: SimulationOrMeshJobNodes
    display_name: Number of nodes to allocate for the OpenFOAM processing jobs
    uint_value: 1
  - name: SimulationOrMeshJobMemory
    display_name: Memory to allocate for the OpenFOAM processing jobs
    string_value: 4GiB
  - name: Coefficients
    display_name: Coefficients to be used in DecomposeParDict. Must be factors of numberOfSubdomains (SimulationOrMeshJobCores * SimulationOrMeshJobNodes).
    string_value: 3 2 1