values:
  - name: OpenFoamVersion
    display_name: Version of OpeanFoam to use. Will be used as the tag for the docker container.
    string_value: "2412"
  - name: OpenFoamContainerUri
    display_name: URI for the OpenFOAM docker image to use for this workflow. Do not include a tag - OpenFoamVersion will be used.
    string_value: docker://opencfd/openfoam-default

  - name: ParaviewContainerUri
    display_name: >-
      URI for Paraview container. If provided the last job in the workflow will start a paraview server you can connect
      to and visualize your results. You will need to set up port forwarding with the fuzzball cli and connect to port
      ParaviewPort. If empty, no paraview server will be started.
    string_value: docker://kitware/paraview-for-ci:v5.13
  - name: ParaviewPort
    display_name: Port used to connect to paraview.
    uint_value: 11111
  - name: ParaviewCores
    display_name: Number of cores to allocate for paraview.
    uint_value: 2
  - name: ParaviewMemory
    display_name: Amount of memory to allocate for paraview.
    string_value: 4GiB
  - name: ParaviewTimeout
    display_name: Max runtime for paraview.
    string_value: 1h

  - name: DataVolume
    display_name: Persistent volume results directory should be saved to. Leave empty skip.
    string_value: volume://user/persistent
  - name: S3Bucket
    display_name: AWS S3 bucket to save data to. Requires S3Secret. Leave empty to skip.
    string_value: ""
  - name: S3Secret
    display_name: Secret URI for access to the S3Bucket (if using AWS S3).
    string_value: ""
  - name: ResultPath
    display_name: Path relative to the DataVolume root and/or the S3 Bucket to save data to.
    string_value: "results/openfoam"
  - name: ResultName
    display_name: Basename of result tar archive (S3) or directory (DataVolume). A timestamp will be appended to create unique file names.
    string_value: openfoam-motorbike


  - name: WmProjectDir
    display_name: Root path of the openfoam lib directory. Do not include version - OpenFoamVersion will be used.
    string_value: /usr/lib/openfoam/openfoam

  - name: UtilityJobCores
    display_name: CPU cores to allocate for the utility jobs.
    uint_value: 1
  - name: UtilityJobMemory
    display_name: Memory to allocate for the utility jobs.
    string_value: 1GiB
  - name: SimulationOrMeshJobCores
    display_name: CPU cores to allocate for the OpenFOAM processing jobs.
    uint_value: 6
  - name: SimulationOrMeshJobNodes
    display_name: Number of nodes to allocate for the OpenFOAM processing jobs.
    uint_value: 1
  - name: SimulationOrMeshJobMemory
    display_name: Memory to allocate for the OpenFOAM processing jobs.
    string_value: 4GiB
  - name: Coefficients
    display_name: Coefficients to be used in DecomposeParDict. Must be factors of numberOfSubdomains (SimulationOrMeshJobCores * SimulationOrMeshJobNodes).
    string_value: 3 2 1
