values:
  - name: OpenFoamVersion
    display_name: Version of OpeanFoam to use. Will be used as the tag for the docker container.
    string_value: "2412"
  - name: OpenFoamContainerUri
    display_name: URI for the OpenFOAM docker image to use for this workflow. Do not include a tag - OpenFoamVersion will be used.
    string_value: docker://opencfd/openfoam-default

  - name: WmProjectDir
    display_name: Root path of the openfoam lib directory. Do not include version - OpenFoamVersion will be used.
    string_value: /usr/lib/openfoam/openfoam

  - name: UtilityJobCores
    display_name: CPU cores to allocate for the utility jobs
    uint_value: 1
  - name: UtilityJobMemory
    display_name: Memory to allocate for the utility jobs
    string_value: 1GiB
  - name: SimulationOrMeshJobCores
    display_name: CPU cores to allocate for the OpenFOAM processing jobs
    uint_value: 6
  - name: SimulationOrMeshJobNodes
    display_name: Number of nodes to allocate for the OpenFOAM processing jobs
    uint_value: 1
  - name: SimulationOrMeshJobMemory
    display_name: Memory to allocate for the OpenFOAM processing jobs
    string_value: 4GiB
  - name: Coefficients
    display_name: Coefficients to be used in DecomposeParDict. Must be factors of numberOfSubdomains (SimulationOrMeshJobCores * SimulationOrMeshJobNodes).
    string_value: 3 2 1
