# Copyright 2025 CIQ, Inc. All rights reserved.
version: v1
### TODO: s3 for egress and experiments

{{- $expurl := trim .ExperimentUrl }}
{{- if not $expurl }}
  {{- fail "ExperimentUrl is required" }}
{{- end }}

{{- $stagein := trim .StageinScript }}
{{- if not $stagein }}
  {{- fail "StageinScript is required" }}
{{- end }}
{{- $lammps := trim .LammpsScript }}
{{- if not $lammps }}
  {{- fail "LammpsScript is required" }}
{{- end }}

{{- $stageout := trim .StageoutScript }}

{{- $scratch_vol := trim .ScratchVolume | default "volume://user/ephemeral" }}
{{- $scratch_mount := "/scratch" }}

{{- $data_vol := trim .DataVolume }}
{{- if (and $stageout (not $data_vol)) }}
  {{- fail "If a stageout script to save data to a data volume is provided a data volume must be specified" }}
{{- end }}
{{- $data_mount := "/data" }}

{{- $run := trim .RunName }}
{{- if not $run }}
  {{- fail "RunName is required" }}
{{- end }}
{{- $run_dir := printf "%s/%s" $scratch_mount $run }}
{{- $out_dir := printf "%s/%s/%s" $data_mount (trim .OutputPath) $run }}

defaults:
  job:
    mounts:
      scratch:
        location: "{{ $scratch_mount }}"

volumes:
  scratch:
    reference: {{ $scratch_vol }}
    ingress:
      - destination:
          uri: file://stagein
        source:
          uri: {{ $expurl }}/{{ $stagein }}
      - destination:
          uri: file://run_lammps
        source:
          uri: {{ $expurl }}/{{ $lammps }}
{{- if $stageout }}
      - destination:
          uri: file://stageout
        source:
          uri: {{ $expurl }}/{{ $stageout }}
  data:
    reference: {{ $data_vol }}
{{- end }}

jobs:
  stagein:
    script: |
      #!/bin/sh
      chmod +x "{{ $scratch_mount }}/stagein"
      "{{ $scratch_mount }}/stagein" "{{ $run_dir }}"
      ls -lh "{{ $scratch_mount }}"
    image:
      uri: docker://alpine:latest
    resource:
      cpu:
        cores: 1
      memory:
        size: 512MiB

  lammps:
    image:
      uri: {{.LammpsContainerUri}}
    depends-on:
      - name: stagein
        status: FINISHED
    script: |
      #!/bin/sh
      chmod +x "{{ $scratch_mount }}/run_lammps"
      "{{ $scratch_mount }}/run_lammps" "{{ $run_dir }}" {{.GPUs}}
      ls -lh "{{ $scratch_mount }}"
    resource:
      cpu:
        cores: {{.Cores}}
        affinity: NUMA
      memory:
        size: {{.Memory}}
      devices:
        nvidia.com/gpu: {{.GPUs}}
{{- if (trim .GPUModel) }}
      annotations:
        {{.GPUModel}}
{{- end }}
    multinode:
      implementation: {{.MpiFlavor}}
      nodes: {{.Nodes}}
    policy:
      timeout:
        execute: {{.Timeout}}

{{- if $stageout }}
  stageout:
    script: |
      #!/bin/sh
      chmod +x "{{ $scratch_mount }}/stageout"
      "{{ $scratch_mount }}/stageout" "{{ $run_dir }}" "{{ $out_dir }}"
    image:
      uri: docker://alpine:latest
    mounts:
      data:
        location: /data
    depends-on:
      - name: lammps
        status: FINISHED
    resource:
      cpu:
        cores: 1
      memory:
        size: 512MiB
{{- end }}
