# Copyright 2025 CIQ, Inc. All rights reserved.
version: v1

{{- $expurl := trim .ExperimentUrl }}
{{- if not $expurl }}
  {{- fail "ExperimentUrl is required" }}
{{- end }}

{{- $stagein := trim .StageinScript }}
{{- if not $stagein }}
  {{- fail "StageinScript is required" }}
{{- end }}
{{- $lammps_script := trim .LammpsScript }}
{{- if not $lammps_script }}
  {{- fail "LammpsScript is required" }}
{{- end }}

{{- $stageout := trim .StageoutScript }}

{{- $scratch_vol := trim .ScratchVolume | default "volume://user/ephemeral" }}
{{- $scratch_mount := "/scratch" }}

## TODO: allow egress to s3??
{{- $data_vol := trim .DataVolume }}
{{- if (and $stageout (not $data_vol)) }}
  {{- fail "If a stageout script to save data to a data volume is provided a data volume must be specified" }}
{{- end }}
{{- $data_mount := "/data" }}

{{- $run := trim .RunName }}
{{- $run_dir := printf "%s/%s" $scratch_mount $run }}
{{- $out_dir := printf "%s/%s" $data_mount $run }}

defaults:
  mounts:
    scratch:
      location: "{{ $scratch_mount }}"

volumes:
  scratch:
    reference: {{ $scratch_vol }}
    ingress:
      - destination:
          uri: file://stagein
        source:
          uri: {{ $expurl }}/{{ $stagein }}
      - destination:
          uri: file://run_lammps
        source:
          uri: {{ $expurl }}/{{ $run_lammps }}
{{- if .StageoutScript }}
      - destination:
          uri: file://stageout
        source:
          uri: {{ $expurl }}/{{ $stageout }}
  data:
    reference: {{ $data_vol }}
{{- end }}

jobs:
  stagein:
    script:
      #!/bin/sh
      chmod +x "{{ $scratch_mount }}"/stagein
      "{{ $scratch_mount }}"/stagein "{{ $run_dir }}"
      ls -lh .
    image:
      uri: docker://alpine:latest
    resource:
      cpu:
        cores: 1
      memory:
        size: 512MIB

  run-lammps:
    image:
      uri: {{.LammpsContainerUri}}
    depends-on:
      - name: stagein
        status: FINISHED
    script: |
      #! /bin/sh
      chmod +x "{{ $scratch_mount }}"/run_lammps
      "{{ $scratch_mount }}"/run_lammps
      ls -lh .
    resource:
      cpu:
        cores: {{.Cores}}
        affinity: NUMA
      memory:
        size: {{.Memory}}
      devices:
        nvidia.com/gpu: {{.GPUs}}
    multinode:
      implementation: {{.MpiFlavor}}
      nodes: {{.Nodes}}
      procs-per-node: {{ .GPUs }}
    policy:
      timeout:
        execute: {{.Timeout}}

{{- if .StageoutScript }}
  stageout:
    script:
      #!/bin/sh
      chmod +x "{{ $scratch_mount }}"/stageout
      "{{ $scratch_mount }}"/stageout.sh  "{{ $run_dir }}" "{{ $out_dir }}"
    image:
      uri: docker://alpine:latest
    mounts:
      data:
        location: /data
    depends-on:
      - name: run-lammps
        status: FINISHED
    resource:
      cpu:
        cores: 1
      memory:
        size: 512MIB
{{- end }}
