values:
  - name: "BlastContainerURI"
    display_name: "URI of BLAST container that will be used."
    string_value: "docker://quay.io/biocontainers/blast:2.16.0--h66d330f_4"
  - name: "EdirectContainerURI"
    display_name: "URI of edirect container that will be used to retrieve query and database sequences."
    string_value: "docker://quay.io/biocontainers/entrez-direct:22.4--he881be0_0"
  - name: "Volume"
    display_name: "Where to store BLAST input/output data."
    string_value: "volume://user/ephemeral"
  - name: "RetrieveQuerySequenceCommand"
    display_name: "Command using efetch to retrieve query sequence."
    string_value: "efetch -db protein -format fasta -id P01349 > P01349.fsa"
  - name: "RetrieveDatabaseSequenceCommand"
    display_name: "Command using efetch to retrieve database sequence(s)."
    string_value: "efetch -db protein -format fasta -id Q90523,P80049,P83981,P83982,P83983,P83977,P83984,P83985,P27950 > nurse-shark-proteins.fsa"
  - name: "MakeBlastDatabaseCommand"
    display_name: "Command using makeblastdb to create BLAST database."
    string_value: "makeblastdb -in /data/fasta/nurse-shark-proteins.fsa -dbtype prot -parse_seqids -out nurse-shark-proteins -title 'Nurse shark proteins' -taxid 7801 -blastdb_version 5"
  - name: "BlastCores"
    display_name: "How many CPU cores to allocate to run BLAST"
    uint_value: 8
  - name: "BlastMemory"
    display_name: "How much memory to allocate to run BLAST."
    string_value: "30GiB"
  - name: "BlastQueryFilePath"
    display_name: "Absolute path to BLAST query file."
    string_value: "/data/queries/P01349.fsa"
  - name: "BlastDatabaseFilePath"
    display_name: "Absolute path to BLAST database file."
    string_value: "/data/fasta/nurse-shark-proteins"
  - name: "BlastOutputFilePath"
    display_name: "Absolute path to BLAST output file."
    string_value: "/data/results/blastp.out"
