# Copyright 2025 CIQ, Inc. All rights reserved.
{{- $ver := .AnsysVersion }}
{{- $ansys_version_number := printf "v%s%s" (substr 2 4 $ver) (substr 5 6 $ver) }}
{{- $datamount := "/data" }}
version: v4

volumes:
  data:
    reference: {{.Volume}}
    ingress:
      - source:
          uri: https://ansys13.ansys.com/AnsysInnovationCourses/MBU/AIC1UnderstandingThePhysics/MechanicalStrain/SE03HipImplantAnalysis.zip
        destination:
          uri: file://SE03HipImplantAnalysis.zip

defaults:
  job:
    mounts:
      {{ $datamount }}: data

jobs:
  hip-implant-analysis:
    image:
      uri: {{.AnsysMechanicalContainerURI}}
      secret: {{.AnsysMechanicalContainerOciSecret}}
    env:
      - ANSYSLMD_LICENSE_FILE={{.AnsyslmdLicenseFile}}
    cwd: {{ $datamount }}
    script: |
      #!/bin/sh
      set -e

      WORKDIR="{{ $datamount }}/hip-implant-analysis-$FB_WORKFLOW_ID"
      mkdir -p "$WORKDIR"
      cd "$WORKDIR"

      mv {{ $datamount }}/SE03HipImplantAnalysis.zip .
      unzip SE03HipImplantAnalysis.zip
      unzip SE03HipImplantAnalysis/Completed\ -\ Hip\ Implant\ Analysis.wbpz

      cp Hip\ implant_files/dp0/SYS/MECH/ds.dat ./hip-implant-analysis.dat

      export LD_LIBRARY_PATH={{.AnsysInstallDir}}/{{$ansys_version_number}}/Framework/bin/Linux64:$LD_LIBRARY_PATH
      export PATH={{.AnsysInstallDir}}/{{$ansys_version_number}}/ansys/bin:$PATH

      ansys251 -b -i hip-implant-analysis.dat -np {{.MechanicalCores}} -mpi openmpi
    resource:
      cpu:
        cores: {{.MechanicalCores}}
        affinity: NUMA
      memory:
        size: {{.MechanicalMemory}}
    policy:
      timeout:
        execute: 30m
