values:
  - name: "StageinScript"
    display_name: "URL to a script that sets up a lammps run including a lammps.input file"
    string_value: "https://raw.githubusercontent.com/wresch/lammps_examples/refs/heads/main/level1/lenard-jones-fluid/my-first-input/stagein.sh"
  - name: "StageoutScript"
    display_name: "URL to a script that copies data to S3 or some other location"
    string_value: "https://raw.githubusercontent.com/wresch/lammps_examples/refs/heads/main/stageout.sh"
  - name: "ScratchVolume"
    display_name: "Used during LAMMPS run"
    string_value: "volume://user/ephemeral"
  - name: "OutputVolume"
    display_name: "Persistent volume to store data (if PersistResults is true)"
    string_value: "volume://user/persistent/output"
  - name: "PersistResults"
    display_name: "Copy results as a tarball to a persistent volume"
    bool_value: false
  - name: "RunName"
    display_name: "Name of the run directory passed to the stagein and stageout scripts"
    string_value: "lj-my-first-input"
  - name: "LammpsInputFile"
    display_name: "Name of the main input file created by the stagein script"
    string_value: "input.lammps"
  - name: "LammpsContainerUri"
    display_name: "URI of LAMMPS container that will be used for computation."
    string_value: "docker://lammps/lammps:stable_29Sep2021_rockylinux8_openmpi_py3"
  - name: "LammpsOptions"
    display_name: "Lammps options for run (-in is added automatically)."
    string_value: ""
  - name: "Cores"
    display_name: "How many CPU cores to allocate."
    uint_value: 8
  - name: "Memory"
    display_name: "How much memory to allocate."
    string_value: "32768MiB"
  - name: "Nodes"
    display_name: "How many nodes to allocate."
    uint_value: 2
  - name: "MpiFlavor"
    display_name: "MPI flavor. Options: openmpi, mpich."
    string_value: "openmpi"
  - name: "Timeout"
    display_name: "Maximum runtime."
    string_value: "30m"
