# Copyright 2025 CIQ, Inc. All rights reserved.
version: v1
volumes:
  bwa-data:
     ingress:
      - source:
          uri: {{.ReferenceGenomeURL}}
        destination:
          uri: file:///reference.fa.gz
      - source:
          uri: {{.Read1URL}}
        destination:
          uri: file:///sample_1.fastq.gz
      - source:
          uri: {{.Read2URL}}
        destination:
          uri: file:///sample_2.fastq.gz
    reference: volume://user/ephemeral
jobs:
  bwa-index:
    cwd: /data
    name: bwa-index
    image:
      uri: docker://biocontainers/bwa:v0.7.17_cv1
    mounts:
      bwa-data:
        location: /data
    command:
      - /bin/bash
      - '-c'
      - |
        if [ -f reference.fa.gz ] && [ ! -f reference.fa ]; then
          gunzip -f reference.fa.gz
        fi

        if [ -f reference.fa ] && [ ! -f reference.fa.bwt ]; then
          bwa index reference.fa
        elif [ ! -f reference.fa ]; then
          exit 1
        fi
    resource:
      cpu:
        cores: {{.BwaIndexCpuCores}}
      memory:
        size: {{.BwaIndexMemory}}GiB
    id: job-{{.JobId}}
  bwa-align:
    cwd: /data
    image:
      uri: docker://biocontainers/bwa:v0.7.17_cv1
    mounts:
      bwa-data:
        location: /data
    command:
      - /bin/bash
      - '-c'
      - |
        if [ -f sample_1.fastq.gz ]; then
          gunzip -f sample_1.fastq.gz
        fi

        if [ -f sample_2.fastq.gz ]; then
          gunzip -f sample_2.fastq.gz
        fi

        if [ ! -f sample_1.fastq ] || [ ! -f sample_2.fastq ]; then
          exit 1
        fi

        bwa mem -t {{.BwaAlignThreads}} reference.fa sample_1.fastq sample_2.fastq > aligned.sam

        echo "Alignment Date: $(date)" > aligned.stats.txt
        echo "Reference Genome: {{.ReferenceGenomeName}}" >> aligned.stats.txt
        echo "Total reads: $(grep -v "^@" aligned.sam | wc -l)" >> aligned.stats.txt
        echo "Mapped reads: $(grep -v "^@" aligned.sam | grep -v "XA:Z:" | wc -l)" >> aligned.stats.txt
        echo "File sizes:" >> aligned.stats.txt
        du -h aligned.sam >> aligned.stats.txt

        head -{{.SampleSize}} aligned.sam > aligned_sample.sam
    requires:
      - bwa-index
    resource:
      cpu:
        cores: {{.BwaAlignCpuCores}}
      memory:
        size: {{.BwaAlignMemory}}GiB
  github-upload:
    cwd: /data
    env:
      - GITHUB_TOKEN={{.GithubToken}}
      - GITHUB_REPO={{.GithubRepo}}
      - GITHUB_USERNAME={{.GithubUsername}}
      - GITHUB_EMAIL={{.GithubEmail}}
      - GITHUB_PATH={{.GithubOutputPath}}
      - TARGET_BRANCH={{.GithubBranch}}
    image:
      uri: docker://alpine:latest
    mounts:
      bwa-data:
        location: /data
    command:
      - /bin/sh
      - '-c'
      - |
        apk add --no-cache git curl jq

        export HOME=/data
        git config --global user.email "${GITHUB_EMAIL}"
        git config --global user.name "${GITHUB_USERNAME}"

        git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git /data/repo
        git config --global --add safe.directory /data/repo

        cd /data/repo
        git checkout ${TARGET_BRANCH}

        mkdir -p ${GITHUB_PATH}

        cp /data/aligned_sample.sam ${GITHUB_PATH}/
        cp /data/aligned.stats.txt ${GITHUB_PATH}/

        cat << EOF > ${GITHUB_PATH}/README.md
# BWA Alignment Results
Generated: $(date)

This directory contains a sample of BWA alignment results for {{.ReferenceGenomeName}}.
Only the first {{.SampleSize}} lines of the SAM file are included due to size constraints.
The full SAM file size is approximately $(du -h /data/aligned.sam | cut -f1).
EOF

        TIMESTAMP=$(date +%Y%m%d%H%M%S)

        git add ${GITHUB_PATH}/
        git commit -m "{{.CommitMessagePrefix}} - ${TIMESTAMP}"
        git push origin ${TARGET_BRANCH}
    requires:
      - bwa-align
    resource:
      cpu:
        cores: {{.GithubUploadCpuCores}}
      memory:
        size: {{.GithubUploadMemory}}GiB