# Copyright 2025 CIQ, Inc. All rights reserved.

{{- $root := "/fuzzball" }}
{{- $port := (randInt 10000 30000) }}

{{- if not (trim .Volumes | hasPrefix "volume://") }}
  {{-  fail "At least one volume has to be specified in the Volumes field." }}
{{- end }}
{{- $volumes := splitList "," .Volumes }}

version: v1
volumes:
{{- range $i, $v := $volumes }}
  vol-{{ $i }}:
  {{- $parts := (splitList ":" $v) }}
  {{- if eq (len $parts) 2 }}
    reference: {{ $v }}
  {{- else if eq (len $parts) 3 }}
    reference: {{ index $parts 0 }}:{{ index $parts 1 }}
  {{- else }}
    {{- fail (printf "Invalid volume reference: %s" $v) }}
  {{- end }}
{{- end }}

services:
  dufs:
    image:
      uri: {{ .Container }}
    resource:
      cpu:
        cores: 1
      memory:
        size: 256MiB
    persist: true
    network:
      ports:
        - name: web
          port: {{ $port }}
          protocol: tcp
      endpoints:
        - name: dufs
          port-name: web
          type: path
          protocol: http
          scope: {{ .ServiceScope }}
    mounts:
{{- range $i, $v := $volumes }}
  {{- $parts := splitList ":" $v }}
  {{- if eq (len $parts) 2 }}
      vol-{{ $i }}:
        location: {{ $root }}/{{ trimPrefix "volume://" $v }}
  {{- else }}
      vol-{{ $i }}:
        location: {{ $root }}/{{ index $parts 2 | trimPrefix "/" }}
  {{- end }}
{{- end }}
    script: |
      #!/bin/sh
      dufs \
        --port {{ $port }} \
        --allow-all \
        --path-prefix "${FB_ENDPOINT_PATH_DUFS}" \
        {{ $root }}
