values:
  - name: Volumes
    display_name: |
      Comma separated list of volumes to mount. These are Fuzzball volume references
      such as `volume://user/persistent`. By default the volume would be available
      under its name in the file browser. If you would like to use a custom path for
      a particular volume in the file browser, you can specify it like this:
      `volume://user/persistent:/custom/path`. The leading slash is optional.
    string_value: "volume://user/persistent:data"

  - name: Container
    display_name: dufs container
    string_value: "docker://sigoden/dufs:v0.46.0"
    display_category: Container

  - name: "ServiceScope"
    display_name: |
      Who can access this dufs instance. Defaults to 'user'.
    string_value: user
    options_input:
      options: [user, group, organization]
    display_category: "Access"
