# Copyright 2025 CIQ, Inc. All rights reserved.
{{- $filename := base .InputFileSource | trim }}

version: v4
volumes:
  vol_1:
    name: vol_1
    ingress:
      - source:
          uri: {{.InputFileSource}}
        destination:
          uri: file://{{ .WorkingDirectory | trim | trimPrefix "/data" | trimPrefix "/" }}/{{ $filename }}
    reference: {{ .DataVolume }}

defaults:
  job:
    mounts:
      /data:
        volume: vol_1

jobs:
  fds:
    cwd: /data
    name: fds
    image:
      uri: docker://openbcl/fds
    policy:
      timeout:
        execute: {{.Timeout}}
    script: |
      #!/bin/sh
      mkdir -p {{ .WorkingDirectory }} && cd {{ .WorkingDirectory }} || exit 1
      mpiexec -n {{.Cores}} fds {{ $filename }}
    resource:
      cpu:
        cores: {{.Cores}}
        affinity: SOCKET
      memory:
        size: {{.Memory}}
