# Copyright 2025 CIQ, Inc. All rights reserved.
version: v4
volumes:
  vol_1:
    name: vol_1
    ingress:
      - source:
          uri: {{.InputFileSource}}
        destination:
          uri: {{.InputFileDestination}}
    reference: volume://user/persistent/fds

defaults:
  job:
    mounts:
      /workspace:
        volume: vol_1

jobs:
  fds:
    cwd: /workspace
    name: fds
    image:
      uri: docker://openbcl/fds
    policy:
      timeout:
        execute: {{.Timeout}}
    command:
      - /bin/sh
      - '-c'
      - mpiexec -n {{.Cores}} fds couch.fds
    resource:
      cpu:
        cores: {{.Cores}}
        affinity: SOCKET
      memory:
        size: {{.Memory}}
